config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  
  resources :articles
  
  resources :projects do 
    resources :issues, shallow: true
    resources :activities, shallow: true
  end
  
  root "pages#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :read, Project
      can :manage, Project, user_id: user.id
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  
  validates :name, presence: true
  validates :idendifier, presence: true, uniqueness: true
  
  extend FriendlyId
  friendly_id :idendifier
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :projects
  
  has_one :profile
  accepts_nested_attributes_for :profile
  
  delegate :nickname, :language, :first_name, :last_name, to: :profile
  
  def admin?
    role == "admin"
  end
  
  def pm?
    role == "pm"
  end
  
  def display_name
    if profile.present?
      if nickname.present?
        return nickname
      else 
        return first_name + " " + last_name
      end
    else
      return email.split("@").first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, notice: exception.message
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:edit, :update, :destroy]
    
    def index
      @articles = Article.all
    end
    
    def new
      @article = Article.new
    end
    
    def edit
    end
    
    def create
      @article = Article.new(article_params)

      if @article.save
        # 成功
        redirect_to articles_path, notice: "新增文章成功!"
      else
        # 失敗
        render :new
      end
    end
    
    def update
      if @article.update(article_params)
        # 成功
        redirect_to articles_path, notice: "資料更新成功!"
      else
        # 失敗
        render :edit
      end
    end
    
    def destroy
      @article.destroy if @article
      redirect_to articles_path, notice: "文章資料已刪除!"
    end

    
    private
    
    def article_params
      params.require(:article).permit(:name, :title, :content)
    end
    
    def find_article
      @article = Article.find_by(id: params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  def index
    @projects = Project.all.includes(user: :profile)
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = current_user.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :idendifier, :website, :is_public, :user_id)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    
  before_action :configure_permitted_parameters, only: [:update]

  def edit 
    resource.build_profile if resource.profile.nil?
  end

  private
  def update_resource(resource, params)
    resource.update_without_password(params)
  end
  
  def after_update_path_for(resource)
    edit_user_registration_path
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [profile_attributes: 
      [:id, :last_name, :first_name, :nickname, :language]
    ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def yes_or_no(value)
    if value
      "是"
    else 
      "否"
    end
  end
  
 
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/articles/_form.html.erb
<%= simple_form_for(article) do |f| %>
    <%= f.input :name, label: "發文者姓名" %>
    <%= f.input :title, label: "標題" %>
    <%= f.input :content, label: "內文" %>
    <%= f.submit %>
  <% end %>

app/views/articles/edit.html.erb
<div style="padding:30px;">
</div>
<h1>編輯文章</h1>

  <%= render "form", article: @article %>

  <br />
  <%= link_to '回候選人列表', articles_path , class:"btn btn-outline-secondary btn-lg btn-block" %>
  <br />

app/views/articles/index.html.erb
<div style="padding:30px;">
</div>
<h1>文章列表</h1>

  <%= link_to "新增文章", new_article_path , class:"btn btn-outline-success" %>

  <table class="table">
    <thead>
      <tr>
        <td>發文者姓名</td>
        <td>標題</td>
        <td>內文</td>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
      <tr>
        <td><%= article.name %></td>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td>
          <%= link_to "編輯", edit_article_path(article) , class:"btn btn-outline-dark btn-sm" %>
          <%= link_to "刪除", article_path(article), method: "delete", data: { confirm: "確認刪除" }, class:"btn btn-outline-dark btn-sm"  %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

app/views/articles/new.html.erb
<div style="padding:30px;">
</div>
<h1>新增文章</h1>

  <%= render "form", article: @article %>

  <br />
  <%= link_to '回文章列表', articles_path , class:"btn btn-outline-secondary btn-lg btn-block"  %>
  <br />
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyIpeen</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= render "shared/flash" if notice %>
      <%= yield %> 
      <%= render 'shared/footer' %>
    </div>
  </body>
</html>

app/views/pages/index.html.erb
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1.0, minimum-scale=1.0, maxmum-scale=1.0, width=device-width">
    <!--RWD必要的meta-->
    <script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.3.5/jquery.fancybox.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.3.5/jquery.fancybox.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Knewave" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
  </head>
  
<div class="card-group mt-3 pt-5">
  <div class="card">
    <img class="card-img-top" src="http://f.cl.ly/items/3u053r3Y3Y3S0w3q1R0x/diet.png" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">熱門美食</h5>
      <p class="card-text">中式料理.日式料理.亞洲料理.異國料理.燒烤類.鍋類.咖啡、簡餐、茶.素食.速食料理...</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 1 mins ago</small>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="http://f.cl.ly/items/1U3u0C3k2H3Q0P1g0o10/globe.png" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">熱門旅遊</h5>
      <p class="card-text">一般住宿.特色住宿.自然/生態景點.歷史/人文景點.休閒/遊憩景點.室外運動.室內運動...</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 2 mins ago</small>
    </div>
  </div>
  <div class="card">
    <img class="card-img-top" src="http://f.cl.ly/items/2a1i2a2A010n1M0d363M/shelter.png" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title">熱門體驗</h5>
      <p class="card-text">台中外帶披薩【pizza running】雙人免費體驗.台北【愛的廚房】雙人免費體驗！......</p>
    </div>
    <div class="card-footer">
      <small class="text-muted">Last updated 3 mins ago</small>
    </div>
  </div>
</div>
<br/>

<div class="card-deck">
  <div class="card border-danger mb-3" style="width: 18rem;">
    <img class="card-img-top" src="http://f.cl.ly/items/0G1K3d19192d3B2k2C22/f134d400a7a8043b7cc047be0406e14b6af8bdd920180521110055.png" alt="Card image cap">
    <div class="card-body text-secondary">
      <h5 class="card-title">端午節必吃粽子！  特搜全台26家粽子名店，南北粽特色粽大公開</h5>
      <p class="card-text">端午節不吃粽子要吃什麼！吃粽子最應景，但該吃哪一間呢？特搜全台26家老字號、團購宅配必推名粽，不管是北部粽、南部粽、外省粽、客家粽、甜粽通通網羅。全年度最適合戰南北的時候到了，2018端午節粽子推薦保證打「粽」你的心！</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      <a href="#" class="btn btn-secondary text-light">Go somewhere</a>
    </div>
  </div>
  
  <div class="card border-danger mb-3" style="width: 18rem;">
    <img class="card-img-top" src="http://f.cl.ly/items/1K0g3I1E2Y3N1b20003l/oie_485328AH0l5gAU.jpg" alt="Card image cap">
    <div class="card-body text-secondary">
      <h5 class="card-title">台灣茶藝博覽會</h5>
      <p class="card-text">現今，有越來越多人喜愛喝茶，但你對於喝好茶的認知又有多少呢？現場將集結台灣各地知名高山茶…等的優質商品，就等著你來茗品體驗。<br />
此次《台灣茶藝博覽會》將規劃展出《各地特色名茶》、《專業茶器》、《製茶設備》、《茶加工食品》、《佐茶美食》、《茶工藝文化》、《陶瓷藝品》、《世界養生茶》等多元主題，眾多展場獨家好康優惠只在台灣茶藝博覽會，絕不錯過！</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      <a href="#" class="btn btn-secondary text-light">Go somewhere</a>
    </div>
  </div>
  
  <div class="card border-danger mb-3" style="width: 18rem;">
    <img class="card-img-top" src="http://f.cl.ly/items/3J1i1S1q1k3C3E3H2d0U/oie_4854117g2Ozm92.gif" alt="Card image cap">
    <div class="card-body text-secondary">
      <h5 class="card-title">台北國際素食養生展</h5>
      <p class="card-text">全球正掀起一陣素食風潮，各界領域之名人也紛紛推崇『素食主義』，但在吃素的同時，又要如何才能吃的健康及營養均衡呢？《台北國際素食養生展》將為各位愛好健康蔬食的消費者們帶來不同的素食新體驗，讓所有民眾不只吃的美味更能吃的健康。</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      <a href="#" class="btn btn-secondary text-light">Go somewhere</a>
    </div>
  </div>
</div>
<br/>

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |form| %>
  <%= form.input :name, label: "名稱" %>
  <%= form.input :description, label: "概述" %>
  <%= form.input :idendifier, label: "代碼" %>
  <%= form.input :website, label: "網站首頁" %>
  <%= form.input :is_public, label: "公開" %>
  <%= form.submit %>
<% end %>

app/views/projects/edit.html.erb
<div style="padding:30px;">
</div>
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div style="padding:30px;">
</div>
<h1>Projects</h1>

<table class="table">
  <thead>
    <tr>
      <th>名稱</th>
      <th>擁有者</th>
      <th>概述</th>
      <th>代碼</th>
      <th>Website</th>
      <th>Is public</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project %></td>
        <td><%= project.user.display_name %></td>
        <td><%= project.description %></td>
        <td><%= project.idendifier %></td>
        <td><%= project.website %></td>
        <td><%= yes_or_no(project.is_public) %></td>
        <td>
          <%= link_to '編輯', edit_project_path(project) if can? :update, project %>
        </td>
        <td>
          <%= link_to '刪除', project, method: :delete, data: { confirm: 'Are you sure?' } if can? :destroy, project %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<div style="padding:30px;">
</div>

<h1>建立新專案</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div style="padding:30px;">
</div>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Idendifier:</strong>
  <%= @project.idendifier %>
</p>

<p>
  <strong>Website:</strong>
  <%= @project.website %>
</p>

<p>
  <strong>Is public:</strong>
  <%= @project.is_public %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/shared/_flash.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

app/views/shared/_footer.html.erb
  <div class="p-1 bg-danger"></div>
  <ul class="nav nav-tabs nav-fill" id="myTab" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" id="one-tab" data-toggle="tab" href="#one" role="tab" aria-controls="one" aria-selected="true">最新分享</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="two-tab" data-toggle="tab" href="#two" role="tab" aria-controls="two" aria-selected="false">吃喝玩樂去</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="three-tab" data-toggle="tab" href="#three" role="tab" aria-controls="three" aria-selected="false">服務中心</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="four-tab" data-toggle="tab" href="#four" role="tab" aria-controls="four" aria-selected="false">關注我們</a>
    </li>
  </ul>
  <div class="tab-content" id="myTabContent">
    <div class="tab-pane fade show active" id="one" role="tabpanel" aria-labelledby="one-tab">
      <div class="footService row  pl-5">
        <div class="col-sm">
        <h5>美食旅遊</h5>
  				<ol style="list-style-type:none;">
  					<li><a href="#" data-label="美食旅遊-餐廳">餐廳</a></li>								
  					<li><a href="#" data-label="美食旅遊-網購團購">網購團購</a></li>
  					<li><a href="#" data-label="美食旅遊-包裝食品">包裝食品</a></li>
  					<li><a href="#" data-label="美食旅遊-住宿">住宿</a></li>
  					<li><a href="#" data-label="美食旅遊-景點">景點</a></li>
  					<br />
  					<br />
  				</ol>
        </div>
        <div class="col-sm"> 
        <h5>娛樂藝文</h5>
  				<ol style="list-style-type:none;">								
  				  <li><a href="#" data-label="娛樂藝文-電影">電影</a></li>
  					<li><a href="#" data-label="娛樂藝文-書籍">書籍</a></li>
  				</ol>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="two" role="tabpanel" aria-labelledby="two-tab">
      <div class="footService row pl-5">
        <div class="col-sm">
        <h5>愛評特搜</h5>
  				<ol style="list-style-type:none;">
  					<li><a href="#" data-label="愛評特搜-地圖快搜">地圖快搜</a></li>								
  					<li><a href="#" data-label="愛評特搜-排行榜">排行榜</a></li>
  					<li><a href="#" data-label="愛評特搜-愛吃閃購">愛吃閃購</a></li>
  					<li><a href="#" data-label="愛評特搜-體驗券">體驗券</a></li>
  					<li><a href="#" data-label="愛評特搜-優惠/KoKo 回饋金">優惠/KoKo 回饋金</a></li>
  					<br />
  					<br />
  				</ol>
        </div>
        <div class="col-sm"> 
        <h5>愛評佈告欄</h5>
  				<ol style="list-style-type:none;">								
  				  <li><a href="#" data-label="愛評佈告欄-愛評公告">愛評公告</a></li>
  					<li><a href="#" data-label="愛評佈告欄-活動特區">活動特區</a></li>
  					<li><a href="#" data-label="愛評佈告欄-熱門話題">熱門話題</a></li>
  					<li><a href="#" data-label="愛評佈告欄-精選特輯">精選特輯</a></li>
  					<li><a href="#" data-label="愛評佈告欄-媒體情報">媒體情報</a></li>
  				</ol>
        </div>
      </div>
    </div>
    <div class="tab-pane fade" id="three" role="tabpanel" aria-labelledby="three-tab">
      <div class="footService row pl-5">
        <div class="col-sm">
        <h5>關於愛評</h5>
  				<ol style="list-style-type:none;">
  					<li><a href="#" data-label="關於愛評-關於我們">關於我們</a></li>								
  					<li><a href="#" data-label="關於愛評-網站地圖">網站地圖</a></li>
  					<li><a href="#" data-label="關於愛評-服務條款">服務條款</a></li>
  					<li><a href="#" data-label="關於愛評-資訊安全政策">資訊安全政策</a></li>
  					<li><a href="#" data-label="關於愛評-線上徵才">線上徵才</a></li>
  					<li><a href="#" data-label="關於愛評-廣告服務">廣告服務</a></li>
  					<li><a href="#">合作提案</a></li>
  				</ol>
        </div>
        <div class="col-sm"> 
        <h5>會員專區</h5>
  				<ol style="list-style-type:none;">								
  				  <li><a href="#" data-label="會員專區-加入愛評網">加入愛評網</a></li>
  					<li><a href="#" data-label="會員專區-忘記密碼">會員專區-忘記密碼</a></li>
  				</ol>
        </div>
        <div class="col-sm"> 
        <h5 style="margin-top:5px;">愛評店家專區</h5>
  				<ol style="list-style-type:none;">								
  				  <li><a href="#" data-label="愛評店家專區-合作店家登入">合作店家登入</a></li>
  					<li><a href="#" data-label="愛評店家專區-加入合作店家">加入合作店家</a></li>
  					<li><a href="#">合作店家客服</a></li>
  					<li><a href="#">店家管理工具2.0</a></li>
  				</ol>
        </div>
        <div class="col-sm"> 
        <h5>建議與問題</h5>
  				<ol style="list-style-type:none;">								
  				  <li><a href="#" data-label="建議與問題-會員客服">會員客服</a></li>
  					<li><a href="#">活動客服</a></li>
  					<li><a href="#" data-label="建議與問題-愛評生活通APP客服">愛評生活通APP客服</a></li>
  				</ol>
        </div>
      </div>
    </div>
    <div class="tab-pane fade text-center m-5" id="four" role="tabpanel" aria-labelledby="four-tab">
      <div class="social align-middle"style="margin-top:20px;">   
        <a class="btn-fb " style="display:inline-block;  width:50px;  height:50px;  border-radius:50%;  font-size:35px; text-align: center;   color:#fff;   line-height:52px;   margin:0 15px; background:#4267B2;" 
        href="http://www.facebook.com/" target="_blank">
          <i class="fa fa-facebook"></i>
        </a>
        <a class="btn-ig" style="display:inline-block;  width:50px;  height:50px;  border-radius:50%;  font-size:35px; text-align: center;  color:#fff;   line-height:52px;   margin:0 15px; background:radial-gradient(circle at 30% 107%, #fdf497 0%, #fdf497 5%, #fd5949 45%,#d6249f 60%,#285AEB 90%);" 
        href="http://www.instagram.com/" target="_blank">
          <i class="fab fa-instagram"></i>
        </a>
        <a class="btn-line" style="display:inline-block;  width:50px;  height:50px;  border-radius:50%;  font-size:35px; text-align: center;  color:#fff;   line-height:52px;   margin:0 15px; background:#4BCD6C;" 
        href="https://line.me/ti/p/%40ntq4580m" target="_blank">
          <i class="fa fa-comment" data-text="LINE"></i>
        </a>
        <a class="btn-yb" style="display:inline-block;  width:50px;  height:50px;  border-radius:50%;  font-size:35px; text-align: center;  color:#fff;   line-height:52px;   margin:0 15px; background:#df1c31;" 
        href="http://www.youtube.com/" target="_blank">
          <i class="fa fa-youtube-play"></i>
        </a>
      </div>
    </div>
  </div>
  <br />
<div class="footCopyright text-center col-lg-12 pb-2">
		<div class="Copyright_logo"></div>
			<a href="/introduction.php" class="ga_tracking" data-category="New-footer" data-action="Click" data-label="客誠科技" data-http="/ad/blockclick.php?page=/newcmm/index.php&amp;block=footer&amp;key=39&amp;next=/introduction.php">客誠科技</a>&nbsp;版權所有&copy;2018 KeCheng Technology Ltd., All Rights Reserved.<br/>
			<span>本網站內會員言論僅代表個人觀點，不代表本站同意其說法，本站不承擔由該言論引起的法律責任</span>
			<p>著作權所有，請勿任意傳載本網站內容</p>
	</div>

<br />

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #e8414d; font-family: 'Knewave', cursive; font-size:36px;">
  <%= link_to "My iPeen", root_path, class: "navbar-brand p-2" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "網站首頁", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "文章清單", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "專案清單", projects_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav mr-0">
        <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href="#">目前登入 <%= current_user.display_name %></a>
            </li>
            <li class="nav-item">
              <%= link_to "我的帳戶", edit_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "登出", destroy_user_session_path, method: "delete", class: "nav-link" %>
            </li>
        <% else %>
            <li class="nav-item">
              <%= link_to "註冊", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "登入", new_user_session_path, class: "nav-link" %>
            </li>        
        <% end %>
        
    </ul>
  </div>
</nav>